[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "roveac"
authors = [{name = "Adam Lehavi", email = "adamlehavi@gmail.com"}]
dynamic = ["version", "description"]
readme = "README.rst"